export const HOTELS_GRANADA = [
  {
    nombreHotel: 'Boutique Hotel Luna Granada Centro',
    distanciaCentro: '500 m',
    estrellas: 4,
    price: '€57',
    opinion: '9.2/10',
    features: 'Piscina, restaurante, aire acondicionado',
    parking: true,
    web: 'https://boutiquehotellunagranadacentro.com-hotel.com/es/',
    selected: true,
  },
  {
    nombreHotel: 'Seda Club Hotel',
    distanciaCentro: '800 m',
    estrellas: 5,
    price: '€160',
    opinion: '9.6/10',
    features: 'Terraza, restaurante, lujo',
    parking: true,
    web: 'https://www.sedaclubhotel.com',
    selected: false,
  },
  {
    nombreHotel: 'Carmen de la Alcubilla del Caracol',
    distanciaCentro: '900 m',
    estrellas: 'Boutique',
    price: '€110',
    opinion: '9.4/10',
    features: 'Casa granadina, vistas a la Alhambra',
    parking: true,
    web: 'https://www.alcubilladelcaracol.com',
    selected: false,
  },
  {
    nombreHotel: 'La Corrala del Realejo',
    distanciaCentro: '400 m',
    estrellas: 'Boutique',
    price: '€95',
    opinion: '9.2/10',
    features: 'Terraza, aire acondicionado, wifi',
    parking: true,
    web: 'https://www.lacorraladelrealejo.com',
    selected: false,
  },
  {
    nombreHotel: 'Áurea Catedral by Eurostars',
    distanciaCentro: '70 m',
    estrellas: 4,
    price: '€58',
    opinion: '9.3/10',
    features: 'Frente a la catedral, wifi gratuito',
    parking: false,
    web: 'https://www.eurostarshotels.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Santa Isabel La Real',
    distanciaCentro: '600 m',
    estrellas: 'Boutique',
    price: '€100',
    opinion: '9.3/10',
    features: 'Casa histórica, vistas espectaculares',
    parking: false,
    web: 'https://www.hotelsantaisabellareal.com',
    selected: false,
  },
  {
    nombreHotel: 'Bubaqia House - Suites Boutique',
    distanciaCentro: '700 m',
    estrellas: 'Boutique',
    price: '€90',
    opinion: '9.5/10',
    features: 'Suites modernas, cerca del Albaicín',
    parking: false,
    web: 'https://www.bubaqiahouse.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Casa 1800 Granada',
    distanciaCentro: '300 m',
    estrellas: 'Boutique',
    price: '€105',
    opinion: '9.4/10',
    features: 'Casa histórica, desayuno incluido',
    parking: false,
    web: 'https://www.hotelcasa1800granada.com',
    selected: false,
  },
  {
    nombreHotel: 'Gar Anat Hotel Boutique',
    distanciaCentro: '600 m',
    estrellas: 'Boutique',
    price: '€115',
    opinion: '9.1/10',
    features: 'Edificio histórico, biblioteca, habitaciones temáticas',
    parking: true,
    web: 'https://www.hotelgaranat.com',
    selected: false,
  },
  {
    nombreHotel: 'Shine Albayzín',
    distanciaCentro: '800 m',
    estrellas: 'Boutique',
    price: '€120',
    opinion: '9.0/10',
    features: 'Vistas a la Alhambra, edificio histórico',
    parking: true,
    web: 'https://shinehotels.com/hotel-shine-albayzin-granada-2/',
    selected: false,
  },
  {
    nombreHotel: 'Villa Oniria',
    distanciaCentro: '700 m',
    estrellas: 4,
    price: '€130',
    opinion: '8.8/10',
    features: 'Spa, jardín, restaurante gourmet',
    parking: true,
    web: 'https://www.villaoniria.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Comfort Dauro 2',
    distanciaCentro: '500 m',
    estrellas: 3,
    price: '€75',
    opinion: '8.7/10',
    features: 'Bar de tapas, terraza, edificio clásico',
    parking: true,
    web: 'https://www.hotelcomfortdauro2.com/es/',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Puerta De Las Granadas',
    distanciaCentro: '400 m',
    estrellas: 3,
    price: '€85',
    opinion: '9.0/10',
    features: 'Vistas a la Alhambra, edificio del siglo XIX',
    parking: true,
    web: 'https://www.hotelpuertadelasgranadas.com',
    selected: false,
  },
]

export const HOTELS_CORDOBA = [
  {
    nombreHotel: 'Balcón de Córdoba',
    distanciaCentro: '20 m',
    estrellas: 'Boutique',
    price: '€140',
    opinion: '9.3/10',
    features: 'Vistas a la Mezquita, edificio histórico, terraza',
    parking: true,
    web: 'https://www.balcondecordoba.com',
    selected: true,
  },
  {
    nombreHotel: 'Las Casas de la Judería de Córdoba',
    distanciaCentro: '250 m',
    estrellas: 4,
    price: '€122',
    opinion: '9.1/10',
    features: 'Patios andaluces, piscina, arquitectura tradicional',
    parking: true,
    web: 'https://www.hotellascasasdelajuderia.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Boutique Patio del Posadero',
    distanciaCentro: '800 m',
    estrellas: 'Boutique',
    price: '€79',
    opinion: '9.5/10',
    features: 'Piscina, decoración romántica, desayuno gourmet',
    parking: false,
    web: 'https://www.patiodelposadero.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel Madinat',
    distanciaCentro: '300 m',
    estrellas: 'Boutique',
    price: '€130',
    opinion: '9.1/10',
    features: 'Hammam, terrazas con vistas, edificio histórico',
    parking: false,
    web: 'https://www.hotelmadinat.com',
    selected: false,
  },
  {
    nombreHotel: 'H10 Palacio Colomera',
    distanciaCentro: '100 m',
    estrellas: 4,
    price: '€100',
    opinion: '4.5/5',
    features: 'Jardín, piscina, desayuno buffet',
    parking: true,
    web: 'https://www.h10hotels.com',
    selected: false,
  },
  {
    nombreHotel: 'La Llave de la Judería Hotel Boutique',
    distanciaCentro: '400 m',
    estrellas: 'Boutique',
    price: '€95',
    opinion: '9.2/10',
    features: 'Cerca de la sinagoga, decoración elegante',
    parking: false,
    web: 'https://www.lallavedelajuderia.com',
    selected: false,
  },
  {
    nombreHotel: 'Eurostars Conquistador',
    distanciaCentro: '150 m',
    estrellas: 4,
    price: '€80',
    opinion: '4.4/5',
    features: 'Frente a la Mezquita, patio andaluz',
    parking: true,
    web: 'https://www.eurostarshotels.com',
    selected: false,
  },
  {
    nombreHotel: 'Hotel La Boutique Puerta Osario',
    distanciaCentro: '700 m',
    estrellas: 'Boutique',
    price: '€85',
    opinion: '4.6/5',
    features: 'Patio amueblado, diseño retro, desayuno continental',
    parking: true,
    web: 'http://www.hotellaboutique.com',
    selected: false,
  },
  {
    nombreHotel: 'Hospes Palacio del Bailío',
    distanciaCentro: '900 m',
    estrellas: 5,
    price: '€141',
    opinion: '9.1/10',
    features: 'Palacio del siglo XVI, piscina, jardines',
    parking: true,
    web: 'https://www.hospes.com',
    selected: false,
  },
]
